const char *g_transvoxel_minimal_shader =
"shader_type spatial;\n"
"render_mode unshaded, cull_back;\n"
"\n"
"uniform int u_transition_mask;\n"
"\n"
"uniform sampler2D layer_0;\n"
"uniform sampler2D layer_1;\n"
"uniform sampler2D layer_2;\n"
"uniform sampler2D layer_3;\n"
"\n"
"float get_transition_secondary_factor(int idata) {\n"
"	int transition_mask = u_transition_mask & 0xff;\n"
"	int cell_border_mask = idata & 63;\n"
"	int vertex_border_mask = (idata >> 8) & 63;\n"
"	int m = transition_mask & cell_border_mask;\n"
"	float t = float(m != 0);\n"
"	t *= float((vertex_border_mask & ~transition_mask) == 0);\n"
"	return t;\n"
"}\n"
"\n"
"vec3 get_transition_position(vec3 vertex_pos, vec4 fdata) {\n"
"	int idata = floatBitsToInt(fdata.a);\n"
"	float secondary_factor = get_transition_secondary_factor(idata);\n"
"	vec3 secondary_position = fdata.xyz;\n"
"	vec3 pos = mix(vertex_pos, secondary_position, secondary_factor);\n"
"	int itransition = (idata >> 16) & 0xff;\n"
"	float transition_cull = float(itransition == 0 || (itransition & u_transition_mask) != 0);\n"
"	pos *= transition_cull;\n"
"	return pos;\n"
"}\n"
"\n"
"void vertex() {\n"
"	VERTEX = get_transition_position(VERTEX, CUSTOM0);\n"
"}\n"
"\n"
"void fragment() {\n"
"	int layer_index = int(floor(COLOR.r * 4.0));\n"
"\n"
"	vec3 tex_color;\n"
"	if (layer_index == 0) {\n"
"		tex_color = texture(layer_0, UV).rgb;\n"
"	} else if (layer_index == 1) {\n"
"		tex_color = texture(layer_1, UV).rgb;\n"
"	} else if (layer_index == 2) {\n"
"		tex_color = texture(layer_2, UV).rgb;\n"
"	} else if (layer_index == 3) {\n"
"		tex_color = texture(layer_3, UV).rgb;\n"
"	} else {\n"
"		tex_color = vec3(1.0, 0.0, 1.0); // fucsia: error visual\n"
"	}\n"
"\n"
"	ALBEDO = tex_color;\n"
"}\n";
