// Generated file

// clang-format off
const char *g_transvoxel_minimal_shader =
"shader_type spatial;\n"
"render_mode cull_back;\n"
"\n"
"uniform int u_transition_mask;\n"
"\n"
"uniform sampler2D biome_0;\n"
"uniform sampler2D biome_1;\n"
"uniform sampler2D biome_2;\n"
"uniform sampler2D biome_3;\n"
"\n"
"float get_biome_transvoxel_secondary_factor(int idata) {\n"
"	int transition_mask = u_transition_mask & 0xff;\n"
"	int cell_border_mask = idata & 63;\n"
"	int vertex_border_mask = (idata >> 8) & 63;\n"
"	int m = transition_mask & cell_border_mask;\n"
"	float t = float(m != 0);\n"
"	t *= float((vertex_border_mask & ~transition_mask) == 0);\n"
"	return t;\n"
"}\n"
"\n"
"vec3 get_biome_transvoxel_position(vec3 vertex_pos, vec4 fdata) {\n"
"	int idata = floatBitsToInt(fdata.a);\n"
"	float secondary_factor = get_biome_transvoxel_secondary_factor(idata);\n"
"	vec3 secondary_position = fdata.xyz;\n"
"	vec3 pos = mix(vertex_pos, secondary_position, secondary_factor);\n"
"	int itransition = (idata >> 16) & 0xff;\n"
"	float transition_cull = float(itransition == 0 || (itransition & u_transition_mask) != 0);\n"
"	pos *= transition_cull;\n"
"	return pos;\n"
"}\n"
"\n"
"void vertex() {\n"
"	VERTEX = get_biome_transvoxel_position(VERTEX, CUSTOM0);\n"
"}\n"
"\n"
"void fragment() {\n"
"	int biome_index = int(COLOR.r * 255.0 + 0.5); // Biome codificado en canal R\n"
"	vec3 tex_color;\n"
"\n"
"	if (biome_index == 0) {\n"
"		tex_color = texture(biome_0, UV).rgb;\n"
"	} else if (biome_index == 1) {\n"
"		tex_color = texture(biome_1, UV).rgb;\n"
"	} else if (biome_index == 2) {\n"
"		tex_color = texture(biome_2, UV).rgb;\n"
"	} else {\n"
"		tex_color = texture(biome_3, UV).rgb;\n"
"	}\n"
"\n"
"	ALBEDO = tex_color;\n"
"}\n";
// clang-format on
